name: CI ubuntu-18.04

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build on ubuntu
      run: |
        sudo add-apt-repository ppa:avsm/ppa
        sudo apt update
        sudo apt install build-essential libgmp-dev z3 m4
        sudo apt install opam
        etc/ci_opam_build.sh
    - name: Run core tests
      run: etc/ci_core_tests.sh
